//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace IngresDemoApp {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [System.Xml.Serialization.XmlRootAttribute("RouteDataSet")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class RouteDataSet : System.Data.DataSet {
        
        private routeDataTable tableroute;
        
        private updateRouteDataTable tableupdateRoute;
        
        private System.Data.SchemaSerializationMode _schemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public RouteDataSet() {
            this.BeginInit();
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected RouteDataSet(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["route"] != null)) {
                    base.Tables.Add(new routeDataTable(ds.Tables["route"]));
                }
                if ((ds.Tables["updateRoute"] != null)) {
                    base.Tables.Add(new updateRouteDataTable(ds.Tables["updateRoute"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public routeDataTable route {
            get {
                return this.tableroute;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public updateRouteDataTable updateRoute {
            get {
                return this.tableupdateRoute;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.BrowsableAttribute(true)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override System.Data.DataSet Clone() {
            RouteDataSet cln = ((RouteDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["route"] != null)) {
                    base.Tables.Add(new routeDataTable(ds.Tables["route"]));
                }
                if ((ds.Tables["updateRoute"] != null)) {
                    base.Tables.Add(new updateRouteDataTable(ds.Tables["updateRoute"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new System.Xml.XmlTextReader(stream), null);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableroute = ((routeDataTable)(base.Tables["route"]));
            if ((initTable == true)) {
                if ((this.tableroute != null)) {
                    this.tableroute.InitVars();
                }
            }
            this.tableupdateRoute = ((updateRouteDataTable)(base.Tables["updateRoute"]));
            if ((initTable == true)) {
                if ((this.tableupdateRoute != null)) {
                    this.tableupdateRoute.InitVars();
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "RouteDataSet";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/RouteDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableroute = new routeDataTable();
            base.Tables.Add(this.tableroute);
            this.tableupdateRoute = new updateRouteDataTable();
            base.Tables.Add(this.tableupdateRoute);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeroute() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeupdateRoute() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(System.Xml.Schema.XmlSchemaSet xs) {
            RouteDataSet ds = new RouteDataSet();
            System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
            System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
            xs.Add(ds.GetSchemaSerializable());
            System.Xml.Schema.XmlSchemaAny any = new System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            return type;
        }
        
        public delegate void routeRowChangeEventHandler(object sender, routeRowChangeEvent e);
        
        public delegate void updateRouteRowChangeEventHandler(object sender, updateRouteRowChangeEvent e);
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class routeDataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnrt_airline;
            
            private System.Data.DataColumn columnal_iatacode;
            
            private System.Data.DataColumn columnrt_flight_num;
            
            private System.Data.DataColumn columnrt_depart_from;
            
            private System.Data.DataColumn columnrt_arrive_to;
            
            private System.Data.DataColumn columnrt_depart_at;
            
            private System.Data.DataColumn columnrt_arrive_at;
            
            private System.Data.DataColumn columnrt_arrive_offset;
            
            private System.Data.DataColumn columnrt_flight_day;
            
            private System.Data.DataColumn columnal_name;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public routeDataTable() {
                this.TableName = "route";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal routeDataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected routeDataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn rt_airlineColumn {
                get {
                    return this.columnrt_airline;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn al_iatacodeColumn {
                get {
                    return this.columnal_iatacode;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn rt_flight_numColumn {
                get {
                    return this.columnrt_flight_num;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn rt_depart_fromColumn {
                get {
                    return this.columnrt_depart_from;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn rt_arrive_toColumn {
                get {
                    return this.columnrt_arrive_to;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn rt_depart_atColumn {
                get {
                    return this.columnrt_depart_at;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn rt_arrive_atColumn {
                get {
                    return this.columnrt_arrive_at;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn rt_arrive_offsetColumn {
                get {
                    return this.columnrt_arrive_offset;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn rt_flight_dayColumn {
                get {
                    return this.columnrt_flight_day;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn al_nameColumn {
                get {
                    return this.columnal_name;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public routeRow this[int index] {
                get {
                    return ((routeRow)(this.Rows[index]));
                }
            }
            
            public event routeRowChangeEventHandler routeRowChanging;
            
            public event routeRowChangeEventHandler routeRowChanged;
            
            public event routeRowChangeEventHandler routeRowDeleting;
            
            public event routeRowChangeEventHandler routeRowDeleted;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddrouteRow(routeRow row) {
                this.Rows.Add(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public routeRow AddrouteRow(string rt_airline, string al_iatacode, int rt_flight_num, string rt_depart_from, string rt_arrive_to, System.DateTime rt_depart_at, System.DateTime rt_arrive_at, sbyte rt_arrive_offset, string rt_flight_day, string al_name) {
                routeRow rowrouteRow = ((routeRow)(this.NewRow()));
                rowrouteRow.ItemArray = new object[] {
                        rt_airline,
                        al_iatacode,
                        rt_flight_num,
                        rt_depart_from,
                        rt_arrive_to,
                        rt_depart_at,
                        rt_arrive_at,
                        rt_arrive_offset,
                        rt_flight_day,
                        al_name};
                this.Rows.Add(rowrouteRow);
                return rowrouteRow;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public routeRow FindByrt_airlinert_flight_numrt_flight_day(string rt_airline, int rt_flight_num, string rt_flight_day) {
                return ((routeRow)(this.Rows.Find(new object[] {
                            rt_airline,
                            rt_flight_num,
                            rt_flight_day})));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override System.Data.DataTable Clone() {
                routeDataTable cln = ((routeDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataTable CreateInstance() {
                return new routeDataTable();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnrt_airline = base.Columns["rt_airline"];
                this.columnal_iatacode = base.Columns["al_iatacode"];
                this.columnrt_flight_num = base.Columns["rt_flight_num"];
                this.columnrt_depart_from = base.Columns["rt_depart_from"];
                this.columnrt_arrive_to = base.Columns["rt_arrive_to"];
                this.columnrt_depart_at = base.Columns["rt_depart_at"];
                this.columnrt_arrive_at = base.Columns["rt_arrive_at"];
                this.columnrt_arrive_offset = base.Columns["rt_arrive_offset"];
                this.columnrt_flight_day = base.Columns["rt_flight_day"];
                this.columnal_name = base.Columns["al_name"];
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnrt_airline = new System.Data.DataColumn("rt_airline", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnrt_airline);
                this.columnal_iatacode = new System.Data.DataColumn("al_iatacode", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnal_iatacode);
                this.columnrt_flight_num = new System.Data.DataColumn("rt_flight_num", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnrt_flight_num);
                this.columnrt_depart_from = new System.Data.DataColumn("rt_depart_from", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnrt_depart_from);
                this.columnrt_arrive_to = new System.Data.DataColumn("rt_arrive_to", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnrt_arrive_to);
                this.columnrt_depart_at = new System.Data.DataColumn("rt_depart_at", typeof(System.DateTime), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnrt_depart_at);
                this.columnrt_arrive_at = new System.Data.DataColumn("rt_arrive_at", typeof(System.DateTime), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnrt_arrive_at);
                this.columnrt_arrive_offset = new System.Data.DataColumn("rt_arrive_offset", typeof(sbyte), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnrt_arrive_offset);
                this.columnrt_flight_day = new System.Data.DataColumn("rt_flight_day", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnrt_flight_day);
                this.columnal_name = new System.Data.DataColumn("al_name", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnal_name);
                this.Constraints.Add(new System.Data.UniqueConstraint("Constraint1", new System.Data.DataColumn[] {
                                this.columnrt_airline,
                                this.columnrt_flight_num,
                                this.columnrt_flight_day}, true));
                this.columnrt_airline.AllowDBNull = false;
                this.columnrt_flight_num.AllowDBNull = false;
                this.columnrt_depart_from.AllowDBNull = false;
                this.columnrt_arrive_to.AllowDBNull = false;
                this.columnrt_depart_at.AllowDBNull = false;
                this.columnrt_arrive_at.AllowDBNull = false;
                this.columnrt_arrive_offset.AllowDBNull = false;
                this.columnrt_flight_day.AllowDBNull = false;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public routeRow NewrouteRow() {
                return ((routeRow)(this.NewRow()));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new routeRow(builder);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Type GetRowType() {
                return typeof(routeRow);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.routeRowChanged != null)) {
                    this.routeRowChanged(this, new routeRowChangeEvent(((routeRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.routeRowChanging != null)) {
                    this.routeRowChanging(this, new routeRowChangeEvent(((routeRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.routeRowDeleted != null)) {
                    this.routeRowDeleted(this, new routeRowChangeEvent(((routeRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.routeRowDeleting != null)) {
                    this.routeRowDeleting(this, new routeRowChangeEvent(((routeRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoverouteRow(routeRow row) {
                this.Rows.Remove(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                RouteDataSet ds = new RouteDataSet();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "routeDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class updateRouteDataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnrt_airline;
            
            private System.Data.DataColumn columnrt_flight_num;
            
            private System.Data.DataColumn columnrt_depart_from;
            
            private System.Data.DataColumn columnrt_arrive_to;
            
            private System.Data.DataColumn columnrt_depart_at;
            
            private System.Data.DataColumn columnrt_arrive_at;
            
            private System.Data.DataColumn columnrt_arrive_offset;
            
            private System.Data.DataColumn columnrt_flight_day;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public updateRouteDataTable() {
                this.TableName = "updateRoute";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal updateRouteDataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected updateRouteDataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn rt_airlineColumn {
                get {
                    return this.columnrt_airline;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn rt_flight_numColumn {
                get {
                    return this.columnrt_flight_num;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn rt_depart_fromColumn {
                get {
                    return this.columnrt_depart_from;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn rt_arrive_toColumn {
                get {
                    return this.columnrt_arrive_to;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn rt_depart_atColumn {
                get {
                    return this.columnrt_depart_at;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn rt_arrive_atColumn {
                get {
                    return this.columnrt_arrive_at;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn rt_arrive_offsetColumn {
                get {
                    return this.columnrt_arrive_offset;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn rt_flight_dayColumn {
                get {
                    return this.columnrt_flight_day;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public updateRouteRow this[int index] {
                get {
                    return ((updateRouteRow)(this.Rows[index]));
                }
            }
            
            public event updateRouteRowChangeEventHandler updateRouteRowChanging;
            
            public event updateRouteRowChangeEventHandler updateRouteRowChanged;
            
            public event updateRouteRowChangeEventHandler updateRouteRowDeleting;
            
            public event updateRouteRowChangeEventHandler updateRouteRowDeleted;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddupdateRouteRow(updateRouteRow row) {
                this.Rows.Add(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public updateRouteRow AddupdateRouteRow(string rt_airline, int rt_flight_num, string rt_depart_from, string rt_arrive_to, System.DateTime rt_depart_at, System.DateTime rt_arrive_at, sbyte rt_arrive_offset, string rt_flight_day) {
                updateRouteRow rowupdateRouteRow = ((updateRouteRow)(this.NewRow()));
                rowupdateRouteRow.ItemArray = new object[] {
                        rt_airline,
                        rt_flight_num,
                        rt_depart_from,
                        rt_arrive_to,
                        rt_depart_at,
                        rt_arrive_at,
                        rt_arrive_offset,
                        rt_flight_day};
                this.Rows.Add(rowupdateRouteRow);
                return rowupdateRouteRow;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public updateRouteRow FindByrt_airlinert_flight_numrt_flight_day(string rt_airline, int rt_flight_num, string rt_flight_day) {
                return ((updateRouteRow)(this.Rows.Find(new object[] {
                            rt_airline,
                            rt_flight_num,
                            rt_flight_day})));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override System.Data.DataTable Clone() {
                updateRouteDataTable cln = ((updateRouteDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataTable CreateInstance() {
                return new updateRouteDataTable();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnrt_airline = base.Columns["rt_airline"];
                this.columnrt_flight_num = base.Columns["rt_flight_num"];
                this.columnrt_depart_from = base.Columns["rt_depart_from"];
                this.columnrt_arrive_to = base.Columns["rt_arrive_to"];
                this.columnrt_depart_at = base.Columns["rt_depart_at"];
                this.columnrt_arrive_at = base.Columns["rt_arrive_at"];
                this.columnrt_arrive_offset = base.Columns["rt_arrive_offset"];
                this.columnrt_flight_day = base.Columns["rt_flight_day"];
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnrt_airline = new System.Data.DataColumn("rt_airline", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnrt_airline);
                this.columnrt_flight_num = new System.Data.DataColumn("rt_flight_num", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnrt_flight_num);
                this.columnrt_depart_from = new System.Data.DataColumn("rt_depart_from", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnrt_depart_from);
                this.columnrt_arrive_to = new System.Data.DataColumn("rt_arrive_to", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnrt_arrive_to);
                this.columnrt_depart_at = new System.Data.DataColumn("rt_depart_at", typeof(System.DateTime), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnrt_depart_at);
                this.columnrt_arrive_at = new System.Data.DataColumn("rt_arrive_at", typeof(System.DateTime), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnrt_arrive_at);
                this.columnrt_arrive_offset = new System.Data.DataColumn("rt_arrive_offset", typeof(sbyte), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnrt_arrive_offset);
                this.columnrt_flight_day = new System.Data.DataColumn("rt_flight_day", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnrt_flight_day);
                this.Constraints.Add(new System.Data.UniqueConstraint("updateRouteKey1", new System.Data.DataColumn[] {
                                this.columnrt_airline,
                                this.columnrt_flight_num,
                                this.columnrt_flight_day}, true));
                this.columnrt_airline.AllowDBNull = false;
                this.columnrt_flight_num.AllowDBNull = false;
                this.columnrt_flight_day.AllowDBNull = false;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public updateRouteRow NewupdateRouteRow() {
                return ((updateRouteRow)(this.NewRow()));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new updateRouteRow(builder);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Type GetRowType() {
                return typeof(updateRouteRow);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.updateRouteRowChanged != null)) {
                    this.updateRouteRowChanged(this, new updateRouteRowChangeEvent(((updateRouteRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.updateRouteRowChanging != null)) {
                    this.updateRouteRowChanging(this, new updateRouteRowChangeEvent(((updateRouteRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.updateRouteRowDeleted != null)) {
                    this.updateRouteRowDeleted(this, new updateRouteRowChangeEvent(((updateRouteRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.updateRouteRowDeleting != null)) {
                    this.updateRouteRowDeleting(this, new updateRouteRowChangeEvent(((updateRouteRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveupdateRouteRow(updateRouteRow row) {
                this.Rows.Remove(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                RouteDataSet ds = new RouteDataSet();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "updateRouteDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class routeRow : System.Data.DataRow {
            
            private routeDataTable tableroute;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal routeRow(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableroute = ((routeDataTable)(this.Table));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string rt_airline {
                get {
                    return ((string)(this[this.tableroute.rt_airlineColumn]));
                }
                set {
                    this[this.tableroute.rt_airlineColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string al_iatacode {
                get {
                    try {
                        return ((string)(this[this.tableroute.al_iatacodeColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'al_iatacode\' in table \'route\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableroute.al_iatacodeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int rt_flight_num {
                get {
                    return ((int)(this[this.tableroute.rt_flight_numColumn]));
                }
                set {
                    this[this.tableroute.rt_flight_numColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string rt_depart_from {
                get {
                    return ((string)(this[this.tableroute.rt_depart_fromColumn]));
                }
                set {
                    this[this.tableroute.rt_depart_fromColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string rt_arrive_to {
                get {
                    return ((string)(this[this.tableroute.rt_arrive_toColumn]));
                }
                set {
                    this[this.tableroute.rt_arrive_toColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime rt_depart_at {
                get {
                    return ((System.DateTime)(this[this.tableroute.rt_depart_atColumn]));
                }
                set {
                    this[this.tableroute.rt_depart_atColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime rt_arrive_at {
                get {
                    return ((System.DateTime)(this[this.tableroute.rt_arrive_atColumn]));
                }
                set {
                    this[this.tableroute.rt_arrive_atColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sbyte rt_arrive_offset {
                get {
                    return ((sbyte)(this[this.tableroute.rt_arrive_offsetColumn]));
                }
                set {
                    this[this.tableroute.rt_arrive_offsetColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string rt_flight_day {
                get {
                    return ((string)(this[this.tableroute.rt_flight_dayColumn]));
                }
                set {
                    this[this.tableroute.rt_flight_dayColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string al_name {
                get {
                    if (this.Isal_nameNull()) {
                        return null;
                    }
                    else {
                        return ((string)(this[this.tableroute.al_nameColumn]));
                    }
                }
                set {
                    this[this.tableroute.al_nameColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isal_iatacodeNull() {
                return this.IsNull(this.tableroute.al_iatacodeColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setal_iatacodeNull() {
                this[this.tableroute.al_iatacodeColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isal_nameNull() {
                return this.IsNull(this.tableroute.al_nameColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setal_nameNull() {
                this[this.tableroute.al_nameColumn] = System.Convert.DBNull;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class updateRouteRow : System.Data.DataRow {
            
            private updateRouteDataTable tableupdateRoute;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal updateRouteRow(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableupdateRoute = ((updateRouteDataTable)(this.Table));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string rt_airline {
                get {
                    return ((string)(this[this.tableupdateRoute.rt_airlineColumn]));
                }
                set {
                    this[this.tableupdateRoute.rt_airlineColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int rt_flight_num {
                get {
                    return ((int)(this[this.tableupdateRoute.rt_flight_numColumn]));
                }
                set {
                    this[this.tableupdateRoute.rt_flight_numColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string rt_depart_from {
                get {
                    try {
                        return ((string)(this[this.tableupdateRoute.rt_depart_fromColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'rt_depart_from\' in table \'updateRoute\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableupdateRoute.rt_depart_fromColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string rt_arrive_to {
                get {
                    try {
                        return ((string)(this[this.tableupdateRoute.rt_arrive_toColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'rt_arrive_to\' in table \'updateRoute\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableupdateRoute.rt_arrive_toColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime rt_depart_at {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableupdateRoute.rt_depart_atColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'rt_depart_at\' in table \'updateRoute\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableupdateRoute.rt_depart_atColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime rt_arrive_at {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableupdateRoute.rt_arrive_atColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'rt_arrive_at\' in table \'updateRoute\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableupdateRoute.rt_arrive_atColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sbyte rt_arrive_offset {
                get {
                    try {
                        return ((sbyte)(this[this.tableupdateRoute.rt_arrive_offsetColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'rt_arrive_offset\' in table \'updateRoute\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableupdateRoute.rt_arrive_offsetColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string rt_flight_day {
                get {
                    return ((string)(this[this.tableupdateRoute.rt_flight_dayColumn]));
                }
                set {
                    this[this.tableupdateRoute.rt_flight_dayColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isrt_depart_fromNull() {
                return this.IsNull(this.tableupdateRoute.rt_depart_fromColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setrt_depart_fromNull() {
                this[this.tableupdateRoute.rt_depart_fromColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isrt_arrive_toNull() {
                return this.IsNull(this.tableupdateRoute.rt_arrive_toColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setrt_arrive_toNull() {
                this[this.tableupdateRoute.rt_arrive_toColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isrt_depart_atNull() {
                return this.IsNull(this.tableupdateRoute.rt_depart_atColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setrt_depart_atNull() {
                this[this.tableupdateRoute.rt_depart_atColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isrt_arrive_atNull() {
                return this.IsNull(this.tableupdateRoute.rt_arrive_atColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setrt_arrive_atNull() {
                this[this.tableupdateRoute.rt_arrive_atColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isrt_arrive_offsetNull() {
                return this.IsNull(this.tableupdateRoute.rt_arrive_offsetColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setrt_arrive_offsetNull() {
                this[this.tableupdateRoute.rt_arrive_offsetColumn] = System.Convert.DBNull;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class routeRowChangeEvent : System.EventArgs {
            
            private routeRow eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public routeRowChangeEvent(routeRow row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public routeRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class updateRouteRowChangeEvent : System.EventArgs {
            
            private updateRouteRow eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public updateRouteRowChangeEvent(updateRouteRow row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public updateRouteRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591