/*
**	Copyright (c) 2004 Ingres Corporation
**	All rights reserved.
*/

/**
** Name:	grproc.h -	OC_OBJECT procedure extern declarations.
**
** Description:
**	Generated automatically by classout.
**
** History:
**	Revision 6.2  88/12  wong
**	Deleted Class procedures for Graph only objects.
**
**	Revision 4.0  86/01  peterk
**	Initial revision.
**/
FUNC_EXTERN OOID	COat();
FUNC_EXTERN OOID	COatEnd();
FUNC_EXTERN OOID	COatPut();
FUNC_EXTERN OOID	COcurrentName();
FUNC_EXTERN OOID	COdo();
FUNC_EXTERN OOID	COfirst();
FUNC_EXTERN OOID	COinit();
FUNC_EXTERN OOID	COisEmpty();
FUNC_EXTERN OOID	COnext();
FUNC_EXTERN OOID	COprint();
FUNC_EXTERN OOID	iiooAlloc();
FUNC_EXTERN OOID	iiooClook();
FUNC_EXTERN OOID	iiooCnew();
FUNC_EXTERN OOID	iiooC0new();
FUNC_EXTERN OOID	iiooCDbnew();
FUNC_EXTERN OOID	iiooCperform();
FUNC_EXTERN OOID	iiooCwithName();
FUNC_EXTERN OOID	ENdecode();
FUNC_EXTERN OOID	ENdestroy();
FUNC_EXTERN OOID	ENfetch();
FUNC_EXTERN OOID	ENflush();
FUNC_EXTERN OOID	ENinit();
FUNC_EXTERN OOID	ENinit();
FUNC_EXTERN OOID	ENreadfile();
FUNC_EXTERN OOID	ENwritefile();
FUNC_EXTERN OOID	GRCencode();
FUNC_EXTERN OOID	GRaxinit();
FUNC_EXTERN OOID	GRaxinit();
FUNC_EXTERN OOID	GRbinit();
FUNC_EXTERN OOID	GRbinit();
FUNC_EXTERN OOID	GRcinit();
FUNC_EXTERN OOID	GRcinit();
FUNC_EXTERN OOID	GRdecode();
FUNC_EXTERN OOID	GRdepinit();
FUNC_EXTERN OOID	GRdepinit();
FUNC_EXTERN OOID	GRdestroy();
FUNC_EXTERN OOID	GRencode();
FUNC_EXTERN OOID	GRfetch();
FUNC_EXTERN OOID	GRflush();
FUNC_EXTERN OOID	GRinit();
FUNC_EXTERN OOID	GRinitDb();
FUNC_EXTERN OOID	GRleginit();
FUNC_EXTERN OOID	GRleginit();
FUNC_EXTERN OOID	GRlinit();
FUNC_EXTERN OOID	GRlinit();
FUNC_EXTERN OOID	GRnameOk();
FUNC_EXTERN OOID	GRoptInit();
FUNC_EXTERN OOID	GRoptInit();
FUNC_EXTERN OOID	GRpinit();
FUNC_EXTERN OOID	GRpinit();
FUNC_EXTERN OOID	GRsinit();
FUNC_EXTERN OOID	GRsinit();
FUNC_EXTERN OOID	GRtinit();
FUNC_EXTERN OOID	GRtinit();
FUNC_EXTERN OOID	GRvig1Axd();
FUNC_EXTERN OOID	GRvigAxdat();
FUNC_EXTERN OOID	GRvigBar();
FUNC_EXTERN OOID	GRvigComp();
FUNC_EXTERN OOID	GRvigDepdat();
FUNC_EXTERN OOID	GRvigGraph();
FUNC_EXTERN OOID	GRvigLegend();
FUNC_EXTERN OOID	GRvigLine();
FUNC_EXTERN OOID	GRvigOpt();
FUNC_EXTERN OOID	GRvigPie();
FUNC_EXTERN OOID	GRvigScat();
FUNC_EXTERN OOID	GRvigText();
FUNC_EXTERN OOID	Minit();
FUNC_EXTERN OOID	MinitDb();
FUNC_EXTERN OOID	OBclass();
FUNC_EXTERN OOID	OBcopy();
FUNC_EXTERN OOID	OBcopyId();
FUNC_EXTERN OOID	OBdestroy();
FUNC_EXTERN OOID	OBedit();
FUNC_EXTERN OOID	OBencode();
FUNC_EXTERN OOID	OBinit();
FUNC_EXTERN OOID	OBinit();
FUNC_EXTERN OOID	OBinit();
FUNC_EXTERN OOID	OBinsertrow();
FUNC_EXTERN OOID	OBisEmpty();
FUNC_EXTERN OOID	OBisNil();
FUNC_EXTERN OOID	OBmarkChange();
FUNC_EXTERN OOID	OBname();
FUNC_EXTERN OOID	OBnoMethod();
FUNC_EXTERN OOID	OBprint();
FUNC_EXTERN OOID	OBrename();
FUNC_EXTERN OOID	OBsetPermit();
FUNC_EXTERN OOID	OBsetRefNull();
FUNC_EXTERN OOID	OBsubResp();
FUNC_EXTERN OOID	OBtime();
FUNC_EXTERN OOID	REinit();
FUNC_EXTERN OOID	REinitDb();
FUNC_EXTERN OOID	fetch0();
FUNC_EXTERN OOID	fetchAll();
FUNC_EXTERN OOID	fetchAt();
FUNC_EXTERN OOID	fetchDb();
FUNC_EXTERN OOID	flush0();
FUNC_EXTERN OOID	flushAll();
FUNC_EXTERN OOID	flushAt();
