//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by enterprise.rc
//
#define IDS_TITLE                       1
#define IDS_ALREADYRUNNING              2
#define IDS_NEEDWINDOWS351              3
#define IDS_SUPPORTVERSION              3
#define IDS_INSTALLERUSAGE              4
#define IDS_AREYOUSURE                  5
#define IDS_CREATINGRSPFILE             6
#define IDS_INVALIDINSTALLATIONCODE     7
#define IDS_CANNOTCREATEPROCESS         8
#define IDS_CANNOTCOPYFILE              9
#define IDS_CANNOTCOPYMSIFILE           9
#define IDS_CANNOTUPDATEWIDB            10
#define IDS_RESPONSEFILEDOESNOTEXIST    11
#define IDS_RSPMISSINGINSTALLPATH       12
#define IDS_INVALIDINSTALLATIONPATH     12
#define IDS_INVALIDINSTALLPATH          13
#define IDS_INVALIDINSTANCE             13
#define IDS_RSPMISSINGINSTALLCODE       14
#define IDS_NOENOUGHSPACE               15
#define IDS_CANNOTCOPYCABFILE           16
#define IDS_NOTEMPPATH                  18
#define IDS_WAITDLGTEXT                 19
#define IDS_INSTALLWIFAILED             20
#define IDS_NOTADMINISTRATOR            21
#define IDS_MUSTUPGRADEVER25            22
#define IDS_INGRESRUNNING               23
#define IDS_UPGRADE                     24
#define IDS_INGRESRUNNING2              25
#define IDS_COPYRIGHT                   26
#define IDS_UNKNOWN                     27
#define IDS_LICENSE_TO                  28
#define IDS_SITEID                      29
#define IDS_FINISH_TEXT                 30
#define IDS_DATEFORMAT                  31
#define IDS_DATEFORMATS                 32
#define IDS_DATEFORMATF                 33
#define IDS_SEPARATOR                   34
#define IDS_CANNOTUPDATELICENSE         35
#define IDB_SPLASH256                   100
#define IDD_SPLASHSCREEN                102
#define IDR_HTML_INSTALLMODE            103
#define IDR_HTML_INSTALLTOP             104
#define IDR_HTML_INSTALLMODE1           106
#define IDR_MAINFRAME                   128
#define IDD_WELCOMEDLG                  135
#define IDD_INSTALLCODE                 138
#define IDR_CLOCK_AVI                   140
#define IDD_WAIT_DIALOG                 141
#define IDD_INSTALLMODE                 143
#define IDB_BITMAPTOP                   144
#define IDR_RT_MANIFEST1                146
#define IDD_CHOOSEINSTALLCODE           147
#define IDB_BITMAP1                     149
#define IDB_BITMAP_INFO                 149
#define IDD_DIALOG_INFO                 151
#define IDD_INSTALLTYPE                 152
#define IDD_INSTANCELIST                153
#define IDB_SIDEBAR                     154
#define IDB_BITMAP2                     155
#define IDB_LOGO                        155
#define IDI_ICON_INSTALL                164
#define IDI_ICON_UPGRADE                167
#define IDI_ICON_EXPRESS                171
#define IDI_ICON_ADVANCED               172
#define IDB_BITMAP_WORLD                175
#define IDB_BITMAP_INFO_16              178
#define IDI_ICON2                       180
#define IDI_ICON_MODIFY2                180
#define IDI_ICON_DEFAULT3               184
#define IDI_ICON3                       185
#define IDI_ICON_CUSTOM3                185
#define IDI_ICON1                       186
#define IDB_200                         200
#define IDC_IMAGE                       1000
#define IDC_INSTALLATIONCODE            1001
#define IDC_INSTALLEDLIST               1002
#define IDC_AVI                         1003
#define IDC_TEXT                        1004
#define IDC_STATIC1                     1005
#define IDC_STATIC2                     1006
#define IDC_ANIMATE1                    1008
#define IDC_IMAGE_TOP                   1009
#define IDC_BUTTON1                     1010
#define IDC_BUTTON_INFO                 1010
#define IDC_IMAGE_BLOCK                 1011
#define IDC_RADIO1                      1013
#define IDC_RADIO2                      1014
#define IDC_STATIC10                    1015
#define IDC_RICHEDIT21                  1016
#define IDC_STATIC11                    1017
#define IDC_RADIO_DEFAULT               1018
#define IDC_RADIO_CUSTOM                1019
#define IDC_STATIC_ID                   1020
#define IDC_EDIT_ID                     1021
#define IDS_INSTNAMETITLE               1022
#define IDC_STATIC_INGRES               1023
#define IDS_INSTNAMESUBTITLE            1024
#define IDS_MODETITLE                   1025
#define IDC_INSTANCE_LIST               1025
#define IDS_MODESUBTITLE                1026
#define IDC_CHECK1                      1027
#define IDC_CHECK_AUTOUPGRADE           1027
#define IDC_RADIO_UPGRADE               1028
#define IDC_RADIO_MODIFY                1029
#define IDC_RADIO_INSTALL               1030
#define IDS_INSTALLTYPETITLE            1031
#define IDC_STATIC_GROUP                1031
#define IDS_INSTALLTYPESUBTITLE         1032
#define IDC_SIDE_BAR                    1032
#define IDS_INSTLISTTITLE               1033
#define IDC_TAB1                        1033
#define IDS_INSTLISTSUBTITLE            1034
#define IDC_STATIC_AUTOID               1034
#define IDS_MUSTCHOOSE                  1035
#define IDC_STATIC_AUTOR                1035
#define WIZ97_STRETCH_BANNER            1037
#define IDC_STATIC_INSTALL              1038
#define IDC_STATIC_UPGRADE              1040
#define IDC_STATIC_MODIFY               1041
#define IDC_STATIC_EXPRESS              1042
#define IDC_STATIC_ADVANCED             1043
#define IDC_STATIC_DEFAULT              1044
#define IDC_STATIC_CUSTOM               1045
#define IDC_BITMAP_INFO                 1046
#define IDS_INVALIDUSER			1048

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        187
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif

// Other defines
#define WIZ97_STRETCH_BANNER			1037
