/*
** Copyright (c) 2004 Ingres Corporation
*/
/*
**  eqdefcc.pp
**
**	This file contains function prototypes for all C function calls which 
**	might be generated by the ESQL/C++ preprocessor.  All ESQL/C++ 
**	generated output files will #include the eqdefcc.h header.
**
**	This file declares all runtime C function calls external for the
**	ESQL/C++ preprocessor. This file includes the C function prototype
**	file eqdefc.pp.
**
**  History:
**	18-apr-94 (teresal)
**		Created.
*/

extern "C" {

#include "eqdefc.pp"

}
