/**
** Name: ADFFI_DEFN.H - Contains number of fi's for each op and op type
**
** Description:
**	This file is generated by an awk script which walks through the
**	function instance table.  There are three types of #def'd constants
**	here:
**	    1) ADZ_<fi_type>_TY_FIIDX represents an index into the function
**		instance table where this class of function instances begins.
**	    2) ADO_<op>_CNT gives the number of function instances which have
**		ADI_<op>_OP as their operation (they are assumed to be grouped
**		together in the function instance table).
**	    3) ADZ_<op>_FIIDX represents an index into the function instance
**	        table specifying where the first function instance which has
**		ADI_<op>_OP as its operation is.
**
**	** DO NOT MAKE MANUAL CHANGES TO THIS FILE **
**
**	All function instances are defined in adf!adg!fi_defn.txt.
**	That file is processed by fi_defn.awk.  To make changes to a
**	function instance, modify fi_defn.txt and run fi_defn.awk;
**/

/* The following operations have no associated function instances */
#define ADO_EXIST_CNT 0
#define ADZ_EXIST_FIIDX ADZ_NOFIIDX

#define ADO_NXIST_CNT 0
#define ADZ_NXIST_FIIDX ADZ_NOFIIDX

#define ADZ_COMPARISON_TY_FIIDX	0

#define ADZ_NE_FIIDX	0
#define ADO_NE_CNT	22

#define ADZ_LT_FIIDX	22
#define ADO_LT_CNT	22

#define ADZ_LE_FIIDX	44
#define ADO_LE_CNT	22

#define ADZ_EQ_FIIDX	66
#define ADO_EQ_CNT	23

#define ADZ_GT_FIIDX	89
#define ADO_GT_CNT	22

#define ADZ_GE_FIIDX	111
#define ADO_GE_CNT	22

#define ADZ_ISNUL_FIIDX	133
#define ADO_ISNUL_CNT	13

#define ADZ_NONUL_FIIDX	146
#define ADO_NONUL_CNT	13

#define ADZ_LIKE_FIIDX	159
#define ADO_LIKE_CNT	5

#define ADZ_NLIKE_FIIDX	164
#define ADO_NLIKE_CNT	5

#define ADZ_ISINT_FIIDX	169
#define ADO_ISINT_CNT	1

#define ADZ_NOINT_FIIDX	170
#define ADO_NOINT_CNT	1

#define ADZ_ISDEC_FIIDX	171
#define ADO_ISDEC_CNT	1

#define ADZ_NODEC_FIIDX	172
#define ADO_NODEC_CNT	1

#define ADZ_ISFLT_FIIDX	173
#define ADO_ISFLT_CNT	1

#define ADZ_NOFLT_FIIDX	174
#define ADO_NOFLT_CNT	1

#define ADZ_OPERATOR_TY_FIIDX	175

#define ADZ_MUL_FIIDX	175
#define ADO_MUL_CNT	18

#define ADZ_POW_FIIDX	193
#define ADO_POW_CNT	2

#define ADZ_ADD_FIIDX	195
#define ADO_ADD_CNT	31

#define ADZ_SUB_FIIDX	226
#define ADO_SUB_CNT	12

#define ADZ_DIV_FIIDX	238
#define ADO_DIV_CNT	18

#define ADZ_PLUS_FIIDX	256
#define ADO_PLUS_CNT	5

#define ADZ_MINUS_FIIDX	261
#define ADO_MINUS_CNT	5

#define ADZ_AGG_FUNC_TY_FIIDX	266

#define ADZ_ANY_FIIDX	266
#define ADO_ANY_CNT	13

#define ADZ_AVG_FIIDX	279
#define ADO_AVG_CNT	5

#define ADZ_CNT_FIIDX	284
#define ADO_CNT_CNT	13

#define ADZ_CNTAL_FIIDX	297
#define ADO_CNTAL_CNT	1

#define ADZ_MAX_FIIDX	298
#define ADO_MAX_CNT	13

#define ADZ_MIN_FIIDX	311
#define ADO_MIN_CNT	13

#define ADZ_SUM_FIIDX	324
#define ADO_SUM_CNT	5

#define ADZ_CORR_FIIDX	329
#define ADO_CORR_CNT	1

#define ADZ_COVAR_POP_FIIDX	330
#define ADO_COVAR_POP_CNT	1

#define ADZ_COVAR_SAMP_FIIDX	331
#define ADO_COVAR_SAMP_CNT	1

#define ADZ_REGR_AVGX_FIIDX	332
#define ADO_REGR_AVGX_CNT	1

#define ADZ_REGR_AVGY_FIIDX	333
#define ADO_REGR_AVGY_CNT	1

#define ADZ_REGR_COUNT_FIIDX	334
#define ADO_REGR_COUNT_CNT	1

#define ADZ_REGR_INTERCEPT_FIIDX	335
#define ADO_REGR_INTERCEPT_CNT	1

#define ADZ_REGR_R2_FIIDX	336
#define ADO_REGR_R2_CNT	1

#define ADZ_REGR_SLOPE_FIIDX	337
#define ADO_REGR_SLOPE_CNT	1

#define ADZ_REGR_SXX_FIIDX	338
#define ADO_REGR_SXX_CNT	1

#define ADZ_REGR_SXY_FIIDX	339
#define ADO_REGR_SXY_CNT	1

#define ADZ_REGR_SYY_FIIDX	340
#define ADO_REGR_SYY_CNT	1

#define ADZ_STDDEV_POP_FIIDX	341
#define ADO_STDDEV_POP_CNT	1

#define ADZ_STDDEV_SAMP_FIIDX	342
#define ADO_STDDEV_SAMP_CNT	1

#define ADZ_VAR_POP_FIIDX	343
#define ADO_VAR_POP_CNT	1

#define ADZ_VAR_SAMP_FIIDX	344
#define ADO_VAR_SAMP_CNT	1

#define ADZ_NORM_FUNC_TY_FIIDX	345

#define ADZ_BNTIM_FIIDX	345
#define ADO_BNTIM_CNT	2

#define ADZ_BIOC_FIIDX	347
#define ADO_BIOC_CNT	1

#define ADZ_CHRD_FIIDX	348
#define ADO_CHRD_CNT	1

#define ADZ_CHREQ_FIIDX	349
#define ADO_CHREQ_CNT	1

#define ADZ_CHRRD_FIIDX	350
#define ADO_CHRRD_CNT	1

#define ADZ_CHSIZ_FIIDX	351
#define ADO_CHSIZ_CNT	1

#define ADZ_CHUSD_FIIDX	352
#define ADO_CHUSD_CNT	1

#define ADZ_CHWR_FIIDX	353
#define ADO_CHWR_CNT	1

#define ADZ_CPUMS_FIIDX	354
#define ADO_CPUMS_CNT	1

#define ADZ_BDATE_FIIDX	355
#define ADO_BDATE_CNT	1

#define ADZ_DIOC_FIIDX	356
#define ADO_DIOC_CNT	1

#define ADZ_ETSEC_FIIDX	357
#define ADO_ETSEC_CNT	1

#define ADZ_PFLTC_FIIDX	358
#define ADO_PFLTC_CNT	1

#define ADZ_PHPAG_FIIDX	359
#define ADO_PHPAG_CNT	1

#define ADZ_BTIME_FIIDX	360
#define ADO_BTIME_CNT	1

#define ADZ_VERSN_FIIDX	361
#define ADO_VERSN_CNT	1

#define ADZ_WSPAG_FIIDX	362
#define ADO_WSPAG_CNT	1

#define ADZ_ABS_FIIDX	363
#define ADO_ABS_CNT	4

#define ADZ_ASCII_FIIDX	367
#define ADO_ASCII_CNT	4

#define ADZ_ATAN_FIIDX	371
#define ADO_ATAN_CNT	1

#define ADZ_DBMSI_FIIDX	372
#define ADO_DBMSI_CNT	1

#define ADZ_CHAR_FIIDX	373
#define ADO_CHAR_CNT	4

#define ADZ_CNCAT_FIIDX	377
#define ADO_CNCAT_CNT	19

#define ADZ_TYNAM_FIIDX	396
#define ADO_TYNAM_CNT	1

#define ADZ_COS_FIIDX	397
#define ADO_COS_CNT	1

#define ADZ_DATE_FIIDX	398
#define ADO_DATE_CNT	7

#define ADZ_DPART_FIIDX	405
#define ADO_DPART_CNT	4

#define ADZ_DTRUN_FIIDX	409
#define ADO_DTRUN_CNT	4

#define ADZ_DBA_FIIDX	413
#define ADO_DBA_CNT	1

#define ADZ_DOW_FIIDX	414
#define ADO_DOW_CNT	1

#define ADZ_EXP_FIIDX	415
#define ADO_EXP_CNT	1

#define ADZ_F4_FIIDX	416
#define ADO_F4_CNT	10

#define ADZ_F8_FIIDX	426
#define ADO_F8_CNT	10

#define ADZ_I1_FIIDX	436
#define ADO_I1_CNT	10

#define ADZ_I2_FIIDX	446
#define ADO_I2_CNT	10

#define ADZ_I4_FIIDX	456
#define ADO_I4_CNT	10

#define ADZ_INTVL_FIIDX	466
#define ADO_INTVL_CNT	4

#define ADZ_LEFT_FIIDX	470
#define ADO_LEFT_CNT	10

#define ADZ_LEN_FIIDX	480
#define ADO_LEN_CNT	13

#define ADZ_LOC_FIIDX	493
#define ADO_LOC_CNT	2

#define ADZ_LOG_FIIDX	495
#define ADO_LOG_CNT	1

#define ADZ_LOWER_FIIDX	496
#define ADO_LOWER_CNT	9

#define ADZ_MOD_FIIDX	505
#define ADO_MOD_CNT	1

#define ADZ_MONEY_FIIDX	506
#define ADO_MONEY_CNT	10

#define ADZ_PAD_FIIDX	516
#define ADO_PAD_CNT	6

#define ADZ_RIGHT_FIIDX	522
#define ADO_RIGHT_CNT	10

#define ADZ_SHIFT_FIIDX	532
#define ADO_SHIFT_CNT	9

#define ADZ_SIN_FIIDX	541
#define ADO_SIN_CNT	1

#define ADZ_SIZE_FIIDX	542
#define ADO_SIZE_CNT	13

#define ADZ_SQRT_FIIDX	555
#define ADO_SQRT_CNT	1

#define ADZ_SQZ_FIIDX	556
#define ADO_SQZ_CNT	6

#define ADZ_TEXT_FIIDX	562
#define ADO_TEXT_CNT	4

#define ADZ_TRIM_FIIDX	566
#define ADO_TRIM_CNT	6

#define ADZ_UPPER_FIIDX	572
#define ADO_UPPER_CNT	9

#define ADZ_USRLN_FIIDX	581
#define ADO_USRLN_CNT	1

#define ADZ_USRNM_FIIDX	582
#define ADO_USRNM_CNT	1

#define ADZ_VARCH_FIIDX	583
#define ADO_VARCH_CNT	4

#define ADZ_HEX_FIIDX	587
#define ADO_HEX_CNT	4

#define ADZ_IFNUL_FIIDX	591
#define ADO_IFNUL_CNT	11

#define ADZ_STRUC_FIIDX	602
#define ADO_STRUC_CNT	1

#define ADZ_DGMT_FIIDX	603
#define ADO_DGMT_CNT	1

#define ADZ_CHA12_FIIDX	604
#define ADO_CHA12_CNT	4

#define ADZ_CHEXT_FIIDX	608
#define ADO_CHEXT_CNT	6

#define ADZ_NTRMT_FIIDX	614
#define ADO_NTRMT_CNT	1

#define ADZ_NTRMV_FIIDX	615
#define ADO_NTRMV_CNT	1

#define ADZ_XYZZY_FIIDX	616
#define ADO_XYZZY_CNT	1

#define ADZ_HXINT_FIIDX	617
#define ADO_HXINT_CNT	2

#define ADZ_TB2DI_FIIDX	619
#define ADO_TB2DI_CNT	1

#define ADZ_DI2TB_FIIDX	620
#define ADO_DI2TB_CNT	1

#define ADZ_DVDSC_FIIDX	621
#define ADO_DVDSC_CNT	1

#define ADZ_DEC_FIIDX	622
#define ADO_DEC_CNT	10

#define ADZ_ETYPE_FIIDX	632
#define ADO_ETYPE_CNT	1

#define ADZ_ELENGTH_FIIDX	633
#define ADO_ELENGTH_CNT	1

#define ADZ_LOGKEY_FIIDX	634
#define ADO_LOGKEY_CNT	2

#define ADZ_TABKEY_FIIDX	636
#define ADO_TABKEY_CNT	2

#define ADZ_IFTRUE_FIIDX	638
#define ADO_IFTRUE_CNT	1

#define ADZ_RESTAB_FIIDX	639
#define ADO_RESTAB_CNT	2

#define ADZ_GMTSTAMP_FIIDX	641
#define ADO_GMTSTAMP_CNT	1

#define ADZ_CPNDMP_FIIDX	642
#define ADO_CPNDMP_CNT	1

#define ADZ_BIT_FIIDX	643
#define ADO_BIT_CNT	4

#define ADZ_VBIT_FIIDX	647
#define ADO_VBIT_CNT	4

#define ADZ_ROWCNT_FIIDX	651
#define ADO_ROWCNT_CNT	1

#define ADZ_SESSUSER_FIIDX	652
#define ADO_SESSUSER_CNT	1

#define ADZ_SYSUSER_FIIDX	653
#define ADO_SYSUSER_CNT	1

#define ADZ_INITUSER_FIIDX	654
#define ADO_INITUSER_CNT	1

#define ADZ_ALLOCPG_FIIDX	655
#define ADO_ALLOCPG_CNT	1

#define ADZ_OVERPG_FIIDX	656
#define ADO_OVERPG_CNT	1

#define ADZ_BYTE_FIIDX	657
#define ADO_BYTE_CNT	9

#define ADZ_VBYTE_FIIDX	666
#define ADO_VBYTE_CNT	10

#define ADZ_LOLK_FIIDX	676
#define ADO_LOLK_CNT	2

#define ADZ_PTYPE_FIIDX	678
#define ADO_PTYPE_CNT	1

#define ADZ_SOUNDEX_FIIDX	679
#define ADO_SOUNDEX_CNT	6

#define ADZ_BDATE4_FIIDX	685
#define ADO_BDATE4_CNT	1

#define ADZ_INTEXT_FIIDX	686
#define ADO_INTEXT_CNT	2

#define ADZ_ISDST_FIIDX	688
#define ADO_ISDST_CNT	1

#define ADZ_CURDATE_FIIDX	689
#define ADO_CURDATE_CNT	1

#define ADZ_CURTIME_FIIDX	690
#define ADO_CURTIME_CNT	1

#define ADZ_CURTMSTMP_FIIDX	691
#define ADO_CURTMSTMP_CNT	1

#define ADZ_LCLTIME_FIIDX	692
#define ADO_LCLTIME_CNT	1

#define ADZ_LCLTMSTMP_FIIDX	693
#define ADO_LCLTMSTMP_CNT	1

#define ADZ_SESSION_PRIV_FIIDX	694
#define ADO_SESSION_PRIV_CNT	1

#define ADZ_IITBLSTAT_FIIDX	695
#define ADO_IITBLSTAT_CNT	1

#define ADZ_LVARCH_FIIDX	696
#define ADO_LVARCH_CNT	7

#define ADZ_LBYTE_FIIDX	703
#define ADO_LBYTE_CNT	11

#define ADZ_BIT_ADD_FIIDX	714
#define ADO_BIT_ADD_CNT	1

#define ADZ_BIT_AND_FIIDX	715
#define ADO_BIT_AND_CNT	1

#define ADZ_BIT_NOT_FIIDX	716
#define ADO_BIT_NOT_CNT	1

#define ADZ_BIT_OR_FIIDX	717
#define ADO_BIT_OR_CNT	1

#define ADZ_BIT_XOR_FIIDX	718
#define ADO_BIT_XOR_CNT	1

#define ADZ_IPADDR_FIIDX	719
#define ADO_IPADDR_CNT	8

#define ADZ_HASH_FIIDX	727
#define ADO_HASH_CNT	1

#define ADZ_RANDOMF_FIIDX	728
#define ADO_RANDOMF_CNT	3

#define ADZ_RANDOM_FIIDX	731
#define ADO_RANDOM_CNT	2

#define ADZ_UUID_CREATE_FIIDX	733
#define ADO_UUID_CREATE_CNT	1

#define ADZ_UUID_TO_CHAR_FIIDX	734
#define ADO_UUID_TO_CHAR_CNT	1

#define ADZ_UUID_FROM_CHAR_FIIDX	735
#define ADO_UUID_FROM_CHAR_CNT	4

#define ADZ_UUID_COMPARE_FIIDX	739
#define ADO_UUID_COMPARE_CNT	1

#define ADZ_SUBSTRING_FIIDX	740
#define ADO_SUBSTRING_CNT	18

#define ADZ_UNHEX_FIIDX	758
#define ADO_UNHEX_CNT	4

#define ADZ_TABLEINFO_FIIDX	762
#define ADO_TABLEINFO_CNT	1

#define ADZ_POS_FIIDX	763
#define ADO_POS_CNT	18

#define ADZ_ATRIM_FIIDX	781
#define ADO_ATRIM_CNT	6

#define ADZ_CHLEN_FIIDX	787
#define ADO_CHLEN_CNT	10

#define ADZ_OCLEN_FIIDX	797
#define ADO_OCLEN_CNT	10

#define ADZ_BLEN_FIIDX	807
#define ADO_BLEN_CNT	10

#define ADZ_NCHAR_FIIDX	817
#define ADO_NCHAR_CNT	2

#define ADZ_NVCHAR_FIIDX	819
#define ADO_NVCHAR_CNT	2

#define ADZ_UTF16TOUTF8_FIIDX	821
#define ADO_UTF16TOUTF8_CNT	2

#define ADZ_UTF8TOUTF16_FIIDX	823
#define ADO_UTF8TOUTF16_CNT	2

#define ADZ_I8_FIIDX	825
#define ADO_I8_CNT	10

#define ADZ_COWGT_FIIDX	835
#define ADO_COWGT_CNT	8

#define ADZ_ADTE_FIIDX	843
#define ADO_ADTE_CNT	1

#define ADZ_TMWO_FIIDX	844
#define ADO_TMWO_CNT	1

#define ADZ_TMW_FIIDX	845
#define ADO_TMW_CNT	1

#define ADZ_TME_FIIDX	846
#define ADO_TME_CNT	1

#define ADZ_TSWO_FIIDX	847
#define ADO_TSWO_CNT	1

#define ADZ_TSW_FIIDX	848
#define ADO_TSW_CNT	1

#define ADZ_TSTMP_FIIDX	849
#define ADO_TSTMP_CNT	1

#define ADZ_INDS_FIIDX	850
#define ADO_INDS_CNT	1

#define ADZ_INYM_FIIDX	851
#define ADO_INYM_CNT	1

#define ADZ_YPART_FIIDX	852
#define ADO_YPART_CNT	1

#define ADZ_QPART_FIIDX	853
#define ADO_QPART_CNT	1

#define ADZ_MPART_FIIDX	854
#define ADO_MPART_CNT	1

#define ADZ_WPART_FIIDX	855
#define ADO_WPART_CNT	1

#define ADZ_WIPART_FIIDX	856
#define ADO_WIPART_CNT	1

#define ADZ_DYPART_FIIDX	857
#define ADO_DYPART_CNT	1

#define ADZ_HPART_FIIDX	858
#define ADO_HPART_CNT	1

#define ADZ_MIPART_FIIDX	859
#define ADO_MIPART_CNT	1

#define ADZ_SPART_FIIDX	860
#define ADO_SPART_CNT	1

#define ADZ_MSPART_FIIDX	861
#define ADO_MSPART_CNT	1

#define ADZ_NPART_FIIDX	862
#define ADO_NPART_CNT	1

#define ADZ_ROUND_FIIDX	863
#define ADO_ROUND_CNT	1

#define ADZ_TRUNC_FIIDX	864
#define ADO_TRUNC_CNT	1

#define ADZ_CEIL_FIIDX	865
#define ADO_CEIL_CNT	1

#define ADZ_FLOOR_FIIDX	866
#define ADO_FLOOR_CNT	1

#define ADZ_CHR_FIIDX	867
#define ADO_CHR_CNT	1

#define ADZ_LTRIM_FIIDX	868
#define ADO_LTRIM_CNT	4

#define ADZ_LPAD_FIIDX	872
#define ADO_LPAD_CNT	4

#define ADZ_RPAD_FIIDX	876
#define ADO_RPAD_CNT	4

#define ADZ_REPL_FIIDX	880
#define ADO_REPL_CNT	2

#define ADZ_ACOS_FIIDX	882
#define ADO_ACOS_CNT	1

#define ADZ_ASIN_FIIDX	883
#define ADO_ASIN_CNT	1

#define ADZ_TAN_FIIDX	884
#define ADO_TAN_CNT	1

#define ADZ_PI_FIIDX	885
#define ADO_PI_CNT	1

#define ADZ_SIGN_FIIDX	886
#define ADO_SIGN_CNT	3

#define ADZ_ATAN2_FIIDX	889
#define ADO_ATAN2_CNT	1

#define ADZ_BYTEXT_FIIDX	890
#define ADO_BYTEXT_CNT	4

#define ADZ_COPY_COERCION_TY_FIIDX	894

#define ADZ_COERCION_TY_FIIDX	931
